import React from 'react';

export const metadata = {
  title: "Showcase",
  description: "Generated by create next app",
};
const ShowCasePage = () => {
    return (
        <div>
            <h2>My Show Case</h2>
        </div>
    );
};

export default ShowCasePage;