import Image from "next/image";
import React from "react";

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h2>About Us Page</h2>

      <Image
        src="https://plus.unsplash.com/premium_photo-1777053567975-286409cefe6e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        height={150}
        width={300}
        alt="Me"
      />

      <Image
        src="/images/me.jpg"
        height={150}
        width={300}
        alt="Me"
      />

      <Image
        src="/images/horse.jpeg"
        height={150}
        width={300}
        alt="Horse"
      />

      <Image
        src="/images/boat.JPG"
        height={150}
        width={300}
        alt="Boat"
      />

      <Image
        src="/images/fire.jpeg"
        height={150}
        width={300}
        alt="Fire"
      />
    </div>
  );
};

export default AboutPage;