import React from 'react';

export const metadata = {
  title: "Docs",
  description: "Generated by create next app",
};
const DocsPage = () => {
    return (
        <div>
            <h2>My Nextjs Docs</h2>
        </div>
    );
};

export default DocsPage;