import React from 'react';

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};


const DashboardPage = () => {
    return (
        <div>
            <h2>Dashboard Page</h2>
        </div>
    );
};

export default DashboardPage;